# -*- coding: utf-8 -*-
"""Reconhecimento audio e fala

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kekS52kJ5yMQJYDwTgmfo1rKpaO--yMg
"""

!pip install SpeechRecognition

!apt-get install -y ffmpeg

import speech_recognition as sr
from google.colab import files
import os

def reconhecer_fala(file_path):
    recognizer = sr.Recognizer()
    try:
        with sr.AudioFile(file_path) as source:
            audio = recognizer.record(source)
            try:
                texto = recognizer.recognize_google(audio, language="pt-BR")
                print(f"Você disse: {texto}")
                return texto
            except sr.UnknownValueError:
                print("Desculpe, não entendi o que você disse.")
            except sr.RequestError as e:
                print(f"Erro no serviço de reconhecimento de fala: {e}")
    except Exception as e:
        print(f"Erro ao processar o arquivo: {e}")

print("Faça o upload do arquivo de áudio:")
uploaded = files.upload()

file_name = next(iter(uploaded))

output_file = "audio.wav"
os.system(f"ffmpeg -i \"{file_name}\" \"{output_file}\"")

comando = reconhecer_fala(output_file)


os.remove(file_name)
os.remove(output_file)